env:
  browser: true
  commonjs: true
  es6: true
extends: "eslint:recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: readonly
parserOptions:
  ecmaVersion: 2020
rules: {}
overrides:
  - files: ["*.js"]
    excludedFiles: node_modules/*
